image: node

before_script:
  - npm install --legacy-peer-deps

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
  - npm run generate
  tags:
    - pages
  artifacts:
    paths:
      - public
  only:
    - master
