export default { title: 'AppButton' }

export const plainBlackButton = () => '<app-button type="black" textType="light-text">Plain Black Button with Light Text</app-button>'
export const plainWhiteButton = () => '<app-button type="white" textType="dark-text">Plain White Button with Dark Text</app-button>'
export const primaryButton = () => '<app-button type="primary" textType="accent">Primary Button with Accent Text</app-button>'
export const secondaryButton = () => '<app-button type="secondary" textType="tertiary">Secondary Button with Tertiary Text</app-button>'
export const tertiaryButton = () => '<app-button type="tertiary" textType="secondary">Tertiary Button with Secondary Text</app-button>'
export const accentButton = () => '<app-button type="accent" textType="light-text">Accent Button</app-button>'
export const dangerButton = () => '<app-button type="danger" textType="light-text">Danger Button</app-button>'
export const warningButton = () => '<app-button type="warning" textType="light-text">Warning Button</app-button>'
export const successButton = () => '<app-button type="success" textType="light-text">Success Button</app-button>'
export const tailwindButton = () => '<app-button type="blue" tailwind tailwindBackgroundOpacity="500" textType="light-text">Tailwind Colors Button</app-button>'
export const roundButton = () => '<app-button round textType="light-text">Round Button</app-button>'
export const uppercaseButton = () => '<app-button uppercase textType="light-text">Uppercase Button</app-button>'
export const boldButton = () => '<app-button type="black" textType="light-text" bold>Bold Font</app-button>'
export const borderButton = () => '<app-button type="light" textType="dark-text" border>Border Button</app-button>'
export const borderPrimaryButton = () => '<app-button type="light" textType="dark-text" border borderType="primary">Border Primary Button</app-button>'
export const borderSecondaryButton = () => '<app-button type="light" textType="dark-text" border borderType="secondary">Border Secondary Button</app-button>'
export const borderTertiaryButton = () => '<app-button type="light" textType="dark-text" border borderType="tertiary">Border Tertiary Button</app-button>'
export const borderAccentButton = () => '<app-button type="light" textType="dark-text" border borderType="accent">Border Accent Button</app-button>'
export const borderDangerButton = () => '<app-button type="light" textType="danger" border borderType="danger">Border Danger Button</app-button>'
export const borderWarningButton = () => '<app-button type="light" textType="warning" border borderType="warning">Border Warning Button</app-button>'
export const borderSuccessButton = () => '<app-button type="light" textType="success" border borderType="success">Border Success Button</app-button>'
export const borderThicknessButton = () => '<app-button type="light" textType="dark-text" border borderThickness="4">Border Thickness</app-button>'